//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.19 at 03:36:18 PM CEST 
//


package es.caib.signatura.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.caib.es.signatura.custodia}ResultadoFirmas" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resultadoFirmas"
})
@XmlRootElement(name = "OptionalOutputs", namespace = "http://www.caib.es.signatura.custodia")
public class OptionalOutputs {

    @XmlElement(name = "ResultadoFirmas", namespace = "http://www.caib.es.signatura.custodia")
    protected ResultadoFirmas resultadoFirmas;

    /**
     * Gets the value of the resultadoFirmas property.
     * 
     * @return
     *     possible object is
     *     {@link ResultadoFirmas }
     *     
     */
    public ResultadoFirmas getResultadoFirmas() {
        return resultadoFirmas;
    }

    /**
     * Sets the value of the resultadoFirmas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultadoFirmas }
     *     
     */
    public void setResultadoFirmas(ResultadoFirmas value) {
        this.resultadoFirmas = value;
    }

}
