//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.19 at 03:36:18 PM CEST 
//


package es.caib.signatura.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nivel" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="orden" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="verificada" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{http://www.caib.es.signatura.custodia}ValidacionCertificado" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.caib.es.signatura.custodia}ResultadoRegla" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.caib.es.signatura.custodia}Sello" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nivel",
    "orden",
    "verificada",
    "validacionCertificado",
    "resultadoRegla",
    "sello"
})
@XmlRootElement(name = "ResultadoFirma", namespace = "http://www.caib.es.signatura.custodia")
public class ResultadoFirma {

    @XmlElement(namespace = "http://www.caib.es.signatura.custodia")
    protected int nivel;
    @XmlElement(namespace = "http://www.caib.es.signatura.custodia")
    protected int orden;
    @XmlElement(namespace = "http://www.caib.es.signatura.custodia")
    protected boolean verificada;
    @XmlElement(name = "ValidacionCertificado", namespace = "http://www.caib.es.signatura.custodia")
    protected List<ValidacionCertificado> validacionCertificado;
    @XmlElement(name = "ResultadoRegla", namespace = "http://www.caib.es.signatura.custodia")
    protected List<ResultadoRegla> resultadoRegla;
    @XmlElement(name = "Sello", namespace = "http://www.caib.es.signatura.custodia")
    protected List<Sello> sello;

    /**
     * Gets the value of the nivel property.
     * 
     */
    public int getNivel() {
        return nivel;
    }

    /**
     * Sets the value of the nivel property.
     * 
     */
    public void setNivel(int value) {
        this.nivel = value;
    }

    /**
     * Gets the value of the orden property.
     * 
     */
    public int getOrden() {
        return orden;
    }

    /**
     * Sets the value of the orden property.
     * 
     */
    public void setOrden(int value) {
        this.orden = value;
    }

    /**
     * Gets the value of the verificada property.
     * 
     */
    public boolean isVerificada() {
        return verificada;
    }

    /**
     * Sets the value of the verificada property.
     * 
     */
    public void setVerificada(boolean value) {
        this.verificada = value;
    }

    /**
     * Gets the value of the validacionCertificado property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validacionCertificado property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidacionCertificado().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValidacionCertificado }
     * 
     * 
     */
    public List<ValidacionCertificado> getValidacionCertificado() {
        if (validacionCertificado == null) {
            validacionCertificado = new ArrayList<ValidacionCertificado>();
        }
        return this.validacionCertificado;
    }

    /**
     * Gets the value of the resultadoRegla property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultadoRegla property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultadoRegla().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultadoRegla }
     * 
     * 
     */
    public List<ResultadoRegla> getResultadoRegla() {
        if (resultadoRegla == null) {
            resultadoRegla = new ArrayList<ResultadoRegla>();
        }
        return this.resultadoRegla;
    }

    /**
     * Gets the value of the sello property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sello property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSello().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sello }
     * 
     * 
     */
    public List<Sello> getSello() {
        if (sello == null) {
            sello = new ArrayList<Sello>();
        }
        return this.sello;
    }

}
