//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.19 at 03:36:18 PM CEST 
//


package es.caib.signatura.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.caib.es.signatura.custodia}ResultadoFirma" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="versionJerarquiaFirmas" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resultadoFirma"
})
@XmlRootElement(name = "ResultadoFirmas", namespace = "http://www.caib.es.signatura.custodia")
public class ResultadoFirmas {

    @XmlElement(name = "ResultadoFirma", namespace = "http://www.caib.es.signatura.custodia")
    protected List<ResultadoFirma> resultadoFirma;
    @XmlAttribute
    protected Integer versionJerarquiaFirmas;

    /**
     * Gets the value of the resultadoFirma property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultadoFirma property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultadoFirma().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultadoFirma }
     * 
     * 
     */
    public List<ResultadoFirma> getResultadoFirma() {
        if (resultadoFirma == null) {
            resultadoFirma = new ArrayList<ResultadoFirma>();
        }
        return this.resultadoFirma;
    }

    /**
     * Gets the value of the versionJerarquiaFirmas property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVersionJerarquiaFirmas() {
        return versionJerarquiaFirmas;
    }

    /**
     * Sets the value of the versionJerarquiaFirmas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersionJerarquiaFirmas(Integer value) {
        this.versionJerarquiaFirmas = value;
    }

}
